image: ruby:2.4.1
services:
  - postgres:latest

stages:
  - dependencies
  - test
  - deploy

variables:
  RAILS_ENV: test
  RACK_ENV: test
  DB_HOST: postgres
  DB_USER: postgres
  DB_PASSWORD: ""

dependencies:
  stage: dependencies
  tags:
    - ruby
  script:
    - mkdir -p vendor/bundle/
    - ls -lAh vendor/bundle/
    - bundle check --path=vendor/bundle/ || bundle install --path=vendor/bundle/ --without=production,development,deploy,doc
    - git status --short && test "$(git status --short | grep Gemfile.lock)" = ""
  artifacts:
    expire_in: 31d
    paths:
      - vendor/bundle/

lint:
  stage: test
  tags:
    - ruby
  artifacts:
    paths:
      - rubocop.html
  script:
    - bundle exec rubocop --rails --fail-level=warning --display-cop-names --format=progress --format=offenses --format=html --out="rubocop.html"

test:
  stage: test
  tags:
    - ruby
    - postgres
  artifacts:
    paths:
      - coverage/
  script:
    - bundle exec rake db:create
    - bundle exec rake db:migrate
    - git status --short && test "$(git status --short | grep db/schema.rb)" = ""
    - bundle exec rake assets:precompile
    - bundle exec rake test

staging:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_STAGING_APP_NAME --api-key=$HEROKU_API_KEY
    - "curl -n -X POST https://api.heroku.com/apps/$HEROKU_STAGING_APP_NAME/ps -H \"Accept: application/json\" -H \"Authorization: Bearer ${HEROKU_API_KEY}\" -d \"command=bundle exec rake db:migrate\""
  environment:
    name: staging
  only:
    - develop

production:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_PRODUCTION_APP_NAME --api-key=$HEROKU_API_KEY
    - "curl -n -X POST https://api.heroku.com/apps/$HEROKU_PRODUCTION_APP_NAME/ps -H \"Accept: application/json\" -H \"Authorization: Bearer ${HEROKU_API_KEY}\" -d \"command=bundle exec rake db:migrate\""
  environment:
    name: production
  only:
    - master
