image: ruby:2.4.3
services:
  - postgres:9-alpine

stages:
  - dependencies
  - test
  - deploy

variables:
  RAILS_ENV: test
  RACK_ENV: test
  DB_HOST: postgres
  DB_USER: postgres
  DB_PASSWORD: ""

.dependencies: &dependencies
  before_script:
    - mkdir -p /cache/bundle
    - ls -lAh /cache/bundle
    - bundle check || bundle install --without=production,development,deploy,doc
    - git status --short && test "$(git status --short | grep Gemfile.lock)" = ""

lint:
  <<: *dependencies
  stage: test
  tags:
    - ruby
  artifacts:
    paths:
      - rubocop.html
  script:
    - bundle exec rubocop --rails --fail-level=warning --display-cop-names --format=progress --format=offenses --format=html --out="rubocop.html"

test:
  <<: *dependencies
  stage: test
  tags:
    - ruby
    - postgres
  artifacts:
    paths:
      - coverage/
  script:
    - bundle exec rails db:create
    - bundle exec rails db:migrate
    - git status --short && test "$(git status --short | grep db/schema.rb)" = ""
    - bundle exec rails assets:precompile
    - bundle exec rails test

staging:
  stage: deploy
  tags:
    - ruby
  script:
    - ENVIRONMENT=staging ./bin/deploy
  environment:
    name: staging
  only:
    - master

production:
  stage: deploy
  tags:
    - ruby
  script:
    - ENVIRONMENT=production ./bin/deploy
  environment:
    name: production
  only:
    - master
  when: manual
