AllCops:
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 120

# Disable this cop so we can get better code coverage.
Style/IfUnlessModifier:
  Enabled: false

# Force public/protected/private keyword to be indented at the same level as the def keyword.
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

# Ignore the schema
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'
Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'
Layout/SpaceBeforeFirstArg:
  Exclude:
    - 'db/schema.rb'
Layout/SpaceAroundOperators:
  Exclude:
    - 'db/schema.rb'
Layout/SpaceInsideHashLiteralBraces:
  Exclude:
    - 'db/schema.rb'
Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'
Style/WordArray:
  Exclude:
    - 'db/schema.rb'
